### ISSUE TITLE
Help: Correctly setting up MySQL

### ISSUE THREAD

**Issue by ArcanFire** [jjmassey/Capstone#1]
I am having issues understanding and using MySQL, could I get help on this in person?

**Comment by jjmassey** [comment]
Do you still need help for this?

**Comment by ArcanFire** [comment]
Yes. I think so.

**Comment by DyerWolf** [comment]
We have decided to run MySQL remotely with azure once the website is hosted. we will be able to link the database directly to azure so any updates that get made automatically updates the database so running the database locally is no longer needed.

**Comment by ArcanFire** [comment]
This issue has been fixed, everything runs fine now.
