### ISSUE TITLE
Forms / Logins

### ISSUE THREAD

**Issue by jjmassey** [jjmassey/Capstone#4]

**Comment by jjmassey** [comment]
Have been following a tutorial:

https://www.youtube.com/watch?v=Fc2O3_2kax8&list=PLw02n0FEB3E3VSHjyYMcFadtQORvl1Ssj&index=1

form.as.p is supposedly outdated and does not work with the Django version we are using (2.1)

form.as.p has a built-in login process that I was hoping we could use. Any help would be great if anyone knows about this

**Comment by jjmassey** [comment]
Official Django documentation alleges form.as.p still works but it doesn't seem to work for me. Comments on tutorial also share same issue

Official Django documentation - https://docs.djangoproject.com/en/2.1/topics/forms/

**Comment by ArcanFire** [comment]
Kenton has found a tutorial video online that seems to have a working form that we could implement. Still unsure on why our original attempts didn't work.

Tutorial video - https://www.youtube.com/watch?v=oKCApIrS0Lo
