### ISSUE TITLE
makemigrations Django renaming issue.

### ISSUE THREAD

**Issue by ArcanFire** [jjmassey/Capstone#9]
I'm trying to run python manage.py makemigrations and I'm receiving the following error:

> Did you rename companylisting.category to companylisting.companyName (a CharField)? [y/N]

with .category and .companyName changing every time.

Saying Yes or No both end in the same outcome:

> You are trying to add a non-nullable field 'email' to companylisting without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
> 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
> 2) Quit, and let me add a default in models.py
Select an option:

**Comment by jjmassey** [comment]
Try deleting your migrations folder mate 👍

**Comment by ArcanFire** [comment]
I figured this out before reading your comment.

The solution I came across was navigating to the migrations folder under each apps root folder and deleted the .py files related to the database. Even when the schema is dropped in MySQL Workbench these .py files stay in place. This causes conflicts when you try to migrate again.
